package-lock.json, src/styles/PreNavbar.css
**Issue No: **#1
**Changes Done:**
- Added z-index for PreNavbar
- Corrected Position to sticky
**Result:**
=> Fixed PreNavbar to Sticky

contributing.md
i have created the contributing.md file.
=> Create contributing.md issue no(#26)

README.md
I have Updated the Readme File
@soham0005  Please merge the Pull Request with the label attached
=> Update README.md Issue no #61 Resolved

frontend/src/components/AllRoutes.jsx, frontend/src/components/FAQ-feature/FAQ.jsx, frontend/src/components/PreNavbar.jsx, frontend/src/styles/FAQ.css
=> FAQs-feature

backend/controllers/authController.js, backend/routes/authRoute.js
@soham0005 
@PRathod27 
I have fixed the issue #85 
Added the forgot password functionality to backend so that user can reset their password by inputting email and new password on reset password page.
=> forgot password functionality added

frontend/src/components/AccessoriesMenu.jsx, frontend/src/styles/Accessories.css, frontend/src/styles/StarProduct.css
I added active class for the accessories navbar such that the tab which is opened stays active and fixed the alignment as mentioned. 
closes #25 
I am attaching screenshots for reference:-
=> Fixed alignment of featured section and added active class for the accessories tab 

frontend/src/App.js, frontend/src/components/AllRoutes.jsx, frontend/src/components/page404.jsx, frontend/src/styles/page404.css
Added error page for the website. It has a home page button to redirect to home when clicked.
fixes: #98 
https://github.com/user-attachments/assets/6e726441-5d5f-4962-9757-7114e07fdac0
=> feat: added error page

README.md, backend/.env.example
@soham0005 please merge it , helps contributors.
=> Adding an .env.example file in backend part that helps contributors to understand the code base & also add this to readme also #89

frontend/public/index.html, frontend/src/App.js, frontend/src/components/Scrolltotop.jsx
=> solved issue #106

backend/controllers/authController.js, frontend/src/components/User/Login.jsx, frontend/src/components/User/Signup.jsx
i do a check for proper working with backend 
Here is video for Signin
https://github.com/user-attachments/assets/cccac2a9-9992-4da9-8404-6a6a5d4e5530
Here is video for Signin
https://github.com/user-attachments/assets/96451091-e19b-45d1-a8a8-792cbd9f203a
=> Login Page and signup page  Testing with Backend

frontend/src/components/PreNavbar.jsx, package-lock.json
Clicking on logo will redirect the user to homepage i added the Link tag to the logo
=> redirect to homepage on logo click

frontend/package-lock.json, frontend/package.json, frontend/src/components/Home.jsx, frontend/src/components/contact.jsx, frontend/src/styles/contact.css
Added a contact form for customers.
Once the form is filled it would be converted to email and sent to the customer care email id.
I have created an email id for ElectroKart customer care.
I shared you the credentials of the Gmail account on Discord. Discord username: rahulacer
Fixes: #134 
https://github.com/user-attachments/assets/ddf99256-d993-4dac-988a-a3871f0d475d
=> [FEATURE]: Added customer contact form

backend/.env.example, backend/index.js, backend/package-lock.json, backend/package.json, frontend/.env.sample, frontend/src/components/PreNavbar.jsx, frontend/src/components/User/Login.jsx, frontend/src/components/User/Signup.jsx
I added the logic for Register button as well as for the Profile Icon .
but There are few more changes which i made  There were Problem in Backend Files like Package.json as it do not have any starts scripts . and for index.js (in Backend ) there were one more MongoDb connection request as well as 2 server listen on port 5000 and 3001 so i commented out that one and there were double import in the index.js so i xommend out them also.
and i added a .env file in frontend because in the frontend code you were using hard coded api url for backend which is not good bcz when someone fork your repo they have to chnage files to work the backend (they have to change Login and signup file).Now they have to only paste their backed url in env file and every thing works fine .
here is sc . if anything …
=> Register button and Profile Icon Status Chnaged based on Login Status #153

frontend/package-lock.json, frontend/package.json, frontend/src/components/Footer.jsx, frontend/src/styles/PreFooter.css
This PR addresses the issue of the missing "Subscribe" button and implements the functionality to send a welcome email to new subscribers.
**1.Subscribe Button:**
- Added a "Subscribe" button to the [specific page/section] for users to subscribe to our service.
- Styled the button to match the existing design and layout.
**2.Welcome Email Functionality:**
- Integrated a welcome email system that sends a confirmation and greeting message once a user subscribes.
- The email includes details about their subscription, features, and contact information.
- The email content and structure can be easily modified in the future.
[Screencast from 2024-10-13 10-45-19.webm](https://github.com/user-attachments/assets/ecaf4ac4-67cf-4bc5-8531-a8d955553452)
and screenshot of email
Related Issues:
Fixes …
=> Add Missing Subscribe Button and Implement Welcome Email Functionality

frontend/src/styles/FAQ.css
I have attached preview.
Please let me know if you would like any changes.
=> added scrollbar styling and fixed scrollbar coming

backend/Dockerfile, backend/index.js, docker-compose.yml, frontend/Dockerfile, frontend/package-lock.json, frontend/package.json
fixes #112 
I have added the Dockerfile for the respective frontend and backend folders and also a docker-compose.yml file at the root of the project that builds images of both frontend and backend folders , then connects them to a single network inside docker container with mongoDB and runs on the specified ports.
command to create and run the docker image of the application : docker compose up --build
=> Added Dockerfile and docker-compose.yml

README.md
=> Add contributor to the readme

backend/db.js, backend/index.js, backend/models/schema.js, frontend/package-lock.json, frontend/package.json
Changes noticed :
Double Declaration of dotenv
Database Connection Logic: You are connecting to MongoDB directly in index.js, which can be moved to db.js for clarity.
Schema Definition: You have the schema definitions inside index.js, which can be moved to schema.js.
Changes made:
1) Moved the Schemas: The user, product, and order schemas were initially defined directly in index.js. They have been moved to schema.js, making the index.js file cleaner and focused solely on application logic (setting up routes, middleware, and server).
2) Consolidated Route Imports: Made sure to import route modules for authentication, products, and orders to avoid defining them directly in the index.js.
3) Removed Duplicated Middleware Setup: The setup for express.json() and cors() was repeated; I've …
=> Checked the Schema.js and added a few changes

frontend/src/components/User/Signup.jsx
Fixes #145  Apply validation for password and also passed it into regex check it must have atleast one uppercase, one lowercase, one special character and its minimum length is 8.
Code:
@soham0005 Please review it and merge with labels:)
=> BUG: Apply Password Validation

frontend/src/components/Footer.jsx, frontend/src/styles/Footer.css
#188 
working demo 
https://github.com/user-attachments/assets/a916e410-a16a-4f35-8ce5-422e2bd72158
=> added language translator to the website

.github/workflows/ci-cd.yaml
#177 
provided a high-level description for a CI/CD setup, likely integrating tests, builds, or deployments to streamline the development workflow using GitHub Actions. This is essential for automating processes like:
Running tests on code pushes and pull requests.
Building and deploying the application on merges.
Ensuring consistency and quality of the project through automated checks.
=> Added CI/CD workflow

frontend/src/components/PreNavbar.jsx, frontend/src/components/User/Login.jsx, frontend/src/components/User/Signup.jsx, frontend/src/styles/Login.css
Redesigned the layout of the login and register pages for improved user experience.
Enhanced the visual hierarchy and accessibility.
Updated styles to create a more cohesive design.
Please let me know of any more changes to be added or layout to be improved !
=> Changed the Design of signup and login page

frontend/src/components/Footer.jsx, frontend/src/styles/Footer.css
I compleated the ISSUE #138 
Where I implement "Rate Us" feature. And attached it in Footer. And matches your website color combination as you said.
Here is the demo
https://github.com/user-attachments/assets/10dfcbca-b6fe-4f19-b724-761908b1b6eb
Please merge this ISSUE.
@soham0005 
**Don't forget to add all the labels that present in the ISSUE #138  That is --> *gssoc-ext, hacktoberfest-accepted, label-2*.**
=> Fix the ISSUE #138    Add the 'Rate Us' Feature.

frontend/package-lock.json, frontend/src/components/FAQ-feature/FAQ.jsx
issue #229 
Adding down arrow button to the FAQS , such that user will not confuse where to click to see answer
Before : 
After :
=> feat : Added Down Arrow Icon to the FAQS section

frontend/src/components/Footer.jsx, frontend/src/components/StarProducts.jsx, frontend/src/styles/Footer.css, frontend/src/styles/StarProduct.css
Fixes #142 Improving the footer design and also make it responsive for every screen size.
@soham0005 Please review it and merge with the labels:)
=> Bug: Design & Responsive Footer

frontend/src/components/Footer.jsx
issue fixes #244 
merge my PR with hacktoberfest and gssoc-ext labels, thank you
=> fix: dynamic updater

backend/controllers/authController.js, backend/helpers/authHelper.js, backend/models/otpModel.js, backend/package-lock.json, backend/package.json, backend/routes/authRoutes.js
Created a fully functional backend and routes which send emails with otp and verify it and sends a jwt token back like other authentication.
=> Adding LogIn via OTP #151 (Backend Schema and routes) 

frontend/package-lock.json, frontend/src/components/Footer.jsx, frontend/src/components/GoogleTranslate.css, frontend/src/components/GoogleTranslate.jsx
Closes: #289
https://github.com/user-attachments/assets/a5fd7637-0f10-41d4-9bad-ec334ad26620
=> Multi-Language Support Using Language Translator

frontend/src/App.js, frontend/src/components/AllRoutes.jsx, frontend/src/components/Contributors.css, frontend/src/components/Contributors.jsx, frontend/src/components/Footer.jsx
Closes: #290 
I have added contributor's page that is directly fetching the data from the repo dynamically.
https://github.com/user-attachments/assets/62e54fa9-9e11-4780-8810-7d38a95622c5
=> Added Contributor's Page

frontend/src/components/ExclusiveOffers.jsx, frontend/src/components/Home.jsx, frontend/src/styles/ExclusiveOffers.css
Still better imges are required
=> Changes made to ExclusiveOffers and made it visible. 
